### ISSUE TITLE
How to upload from Arduino? How to create a BIN file for M5Burner?

### ISSUE THREAD

**Issue by bicurico** [marivaaldo/evil-portal-m5stack#2]
Hello,

I managed to compile your code on Arduino (Windows platform).
I changed it so that the display is switched off, as I noticed that the screen easily burns in.
But when I try to upload, I get an error:

"Sketch uses 1119941 bytes (85%) of program storage space. Maximum is 1310720 bytes.
Global variables use 53516 bytes (16%) of dynamic memory, leaving 274164 bytes for local variables. Maximum is 327680 bytes.
esptool.py v4.5.1
Serial port COM12
Connecting....

A serial exception error occurred: Write timeout
Note: This error originates from pySerial. It is likely not a problem with esptool, but with the hardware connection or drivers.
For troubleshooting steps visit: https://docs.espressif.com/projects/esptool/en/latest/troubleshooting.html
Failed uploading: uploading error: exit status 1"

Also, I have no idea how to upload the generated binaries using M5Burner.

I tried https://esp.huhn.me/ but  it won't connect, either.

Thanks,
Vitor

(Obrigado)

**Comment by marivaaldo** [comment]
Please check if COM12 is correctly serial port and If you have correct drivers installed.

**Comment by bicurico** [comment]
Hello,

Yes, I have COM12 selected.

I can burn your binary from M5Burner without issue, but on Arduino, it won’t work. I think the current M5 board library is bad.

**Comment by bicurico** [comment]
Changed to a different computer, installed Arduino IDE and all libraries and now the Cardputer is recognized by Windows as COM3-USB and the upload works.

Not sure what went wrong on my main computer.

Sorry for bothering.

**Comment by marivaaldo** [comment]
Great! No problems! Good luck.

**Comment by bicurico** [comment]
Just to finish this question and eventually help others:

The problem was that the Cardputer was recognized as COM12. For some reason, that did not work with Arduino.
I changed it to COM8 and after a reboot it started working.
Interestingly, the Cardputer works directly with Microsoft drivers (USB/COM) and the Silicon Labs drivers did not work at all.

**Comment by marivaaldo** [comment]
Thanks for share your problem with solution.
