### ISSUE TITLE
SD card problem

### ISSUE THREAD

**Issue by hiurequeiroz** [marivaaldo/evil-portal-m5stack#4]
I got the following error on serial console

`Failed to open file for appending`

**Comment by marivaaldo** [comment]
Hi! How are you? Please, check if you sdcard is maximum of 32gb and formated in FAT32. Thank you!

**Comment by hiurequeiroz** [comment]
Helo Marivaaldo, thanks for the quick reply, and of course for the great work with the evil-portal.

I've had a curious case here, I have a 32GB class10 SD card from SkanDisk and Fat32 everything right and it didn't work in the cardputer.
I can open the card on my computer without any problems, it's apparently fine.
But I realized it was a very specific problem with this card because I used another card that is also Skandisk class10 32GB and FAT32 and it worked.
